testing rating system

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,8 +27,14 @@ jobs:
         id: tests
         run: |
           npm ci
-          echo "::set-output name=test-output::$(npm test)"
-          echo "${{ join(steps.tests.outputs.*, '\n') }}"
+          npm test
+
+      - name: report test results
+      - uses: actions/upload-artifact@v2  # upload test results
+          if: success() || failure()        # run this step even if previous step failed
+          with:
+            name: test-results
+            path: jest-junit.json
 
       - name: Rate tests
         uses: distributhor/workflow-webhook@v2
